variables:
  RUSTFLAGS: '-C link-arg=-s'
stages:
  - build
build:
  image: rust:1.58.1
  stage: build
  variables:
    RUSTFLAGS: '-C link-arg=-s'
  script:
    - rustup target add wasm32-unknown-unknown
    - cargo build --target wasm32-unknown-unknown --release